#pragma once

enum ShaderName
{
	DepthOpaqueVV,
	DepthMaskedVV,
	DepthMaskedP,
	MeshVV,
	MeshOpaqueP,
	MeshMaskedP,
	MeshletCullC,
	MeshXluVV,
	MeshXluP,
	VisibilityOpaqueVV,
	VisibilityOpaqueP,
	VisibilityMaskedVV,
	VisibilityMaskedP,
	VisibilityMesh1stA,
	VisibilityMesh2ndA,
	VisibilityMeshOpaqueM,
	VisibilityMeshOpaqueP,
	VisibilityMeshMaskedM,
	VisibilityMeshMaskedP,
	ClassifyC,
	MatDepthP,
	ClearArgC,
	MaterialTileVV,
	MaterialTileP,
	MaterialTileTriplanarP,
	MaterialResolveLib,
	InitCountC,
	CountC,
	CountSumC,
	BinningC,
	FinalizeC,
	MatGBStandardC,
	MatGBTriplanarC,
	InitBinningTileC,
	BinningTileC,
	TileStandardC,
	TileTriplanarC,
	PrefixSumInitCS,
	PrefixSumC,
	IndirectC,
	SsaoHbaoC,
	SsaoBitmaskC,
	SsgiC,
	SsgiDIC,
	DeinterleaveC,
	DenoiseC,
	DenoiseWithGIC,
	ShadowOpaqueVV,
	ShadowMaskedVV,
	ShadowMaskedP,
	ShadowP,
	BlurP,
	WaterVV,
	WaterUniformP,
	WaterNewtonP,
	WaterNewtonFaceP,
	WaterRaymarchP,
	WaterMipmapC,
	FullscreenVV,
	LightingSMC,
	LightingEVSMC,
	GenVrsC,
	ClearVrsC,
	ReprojectVrsC,
	ClearMipC,
	FeedbackMipC,
	DepthReductionP,
	DepthReductionC,
	UpscaleP,
	TonemapP,
	MotionVectorC,
	MakeIrradianceC,
	RTProbeTraceLib,
	RTMonteCarloGILib,
	RTRestirGILib,
	RTSpatialReuseC,
	RTResolveGIC,
	RTMaterialLib,
	ApplyDDGI,
	DDGIDebugVV,
	DDGIDebugP,
	SVGFPrepass,
	SVGFTemporal,
	SVGFAtrous,
	XessVelocityC,
	NormalToDerivC,
	TriplanarVV,
	TriplanarP,
	DebugP,

	MAX
};

static const char* kShaderFileAndEntry[] = {
	"mesh/depth_opaque.vv.hlsl",					"main",
	"mesh/depth_masked.vv.hlsl",					"main",
	"mesh/depth_masked.p.hlsl",						"main",
	"mesh/mesh.vv.hlsl",							"main",
	"mesh/mesh_opaque.p.hlsl",						"main",
	"mesh/mesh_masked.p.hlsl",						"main",
	"mesh/meshlet_cull.c.hlsl",						"main",
	"mesh/mesh_xlu.vv.hlsl",						"main",
	"mesh/mesh_xlu.p.hlsl",							"main",
	"visibility/visibility_opaque.vv.hlsl",			"main",
	"visibility/visibility_opaque.p.hlsl",			"main",
	"visibility/visibility_masked.vv.hlsl",			"main",
	"visibility/visibility_masked.p.hlsl",			"main",
	"visibility/visibility_mesh_1st.a.hlsl",		"main",
	"visibility/visibility_mesh_2nd.a.hlsl",		"main",
	"visibility/visibility_mesh_opaque.m.hlsl",		"main",
	"visibility/visibility_mesh_opaque.p.hlsl",		"main",
	"visibility/visibility_mesh_masked.m.hlsl",		"main",
	"visibility/visibility_mesh_masked.p.hlsl",		"main",
	"visibility/classify.c.hlsl",					"main",
	"visibility/material_depth.p.hlsl",				"main",
	"visibility/clear_arg.c.hlsl",					"main",
	"visibility/material_tile.vv.hlsl",				"main",
	"visibility/material_tile.p.hlsl",				"main",
	"visibility/material_tile_triplanar.p.hlsl",	"main",
	"visibility/material_resolve.lib.hlsl",			"main",
	"visibility/material_binning.c.hlsl",			"InitCountCS",
	"visibility/material_binning.c.hlsl",			"CountCS",
	"visibility/material_binning.c.hlsl",			"CountSumCS",
	"visibility/material_binning.c.hlsl",			"BinningCS",
	"visibility/material_binning.c.hlsl",			"FinalizeCS",
	"visibility/material_gbuffer.c.hlsl",			"StandardCS",
	"visibility/material_gbuffer.c.hlsl",			"TriplanarCS",
	"visibility/material_binning.c.hlsl",			"InitBinningTileCS",
	"visibility/material_binning.c.hlsl",			"BinningTileCS",
	"visibility/material_tile.c.hlsl",				"StandardCS",
	"visibility/material_tile.c.hlsl",				"TriplanarCS",
	"visibility/prefix_sum.c.hlsl",					"InitBufferCS",
	"visibility/prefix_sum.c.hlsl",					"PrefixScanCS",
	"ssao/indirect_lighting.c.hlsl",				"main",
	"ssao/ssao_hbao.c.hlsl",						"main",
	"ssao/ssao_bitmask.c.hlsl",						"main",
	"ssao/ssgi_standard.c.hlsl",					"main",
	"ssao/ssgi_deinterleave.c.hlsl",				"main",
	"ssao/deinterleave.c.hlsl",						"main",
	"ssao/denoise.c.hlsl",							"main",
	"ssao/denoise_with_gi.c.hlsl",					"main",
	"shadow/shadow_opaque.vv.hlsl",					"main",
	"shadow/shadow_masked.vv.hlsl",					"main",
	"shadow/shadow_masked.p.hlsl",					"main",
	"shadow/shadow.p.hlsl",							"main",
	"shadow/blur.p.hlsl",							"main",
	"water/water.vv.hlsl",							"main",
	"water/water_uniform.p.hlsl",					"main",
	"water/water_newton.p.hlsl",					"main",
	"water/water_newton_face.p.hlsl",				"main",
	"water/water_raymarch.p.hlsl",					"main",
	"water/water_mipmap.c.hlsl",					"main",
	"util/fullscreen.vv.hlsl",						"main",
	"util/lighting_sm.c.hlsl",						"main",
	"util/lighting_evsm.c.hlsl",					"main",
	"util/vrs.c.hlsl",								"GenerateVrsCS",
	"util/vrs.c.hlsl",								"ClearCS",
	"util/vrs.c.hlsl",								"ReprojectionCS",
	"util/miplevel_feedback.c.hlsl",				"ClearCS",
	"util/miplevel_feedback.c.hlsl",				"FeedbackCS",
	"util/depth_reduction.p.hlsl",					"main",
	"util/depth_reduction.c.hlsl",					"main",
	"util/upscale.p.hlsl",							"main",
	"util/tonemap.p.hlsl",							"main",
	"util/motion_vector.c.hlsl",					"main",
	"util/make_irradiance.c.hlsl",					"main",
	"raytracing/rt_probe_trace.lib.hlsl",			"main",
	"raytracing/rt_monte_carlo_gi.lib.hlsl",		"main",
	"raytracing/rt_restir_gi.lib.hlsl",				"main",
	"raytracing/rt_spatial_reuse.c.hlsl",			"main",
	"raytracing/rt_resolve_gi.c.hlsl",				"main",
	"raytracing/rt_material.lib.hlsl",				"main",
	"ddgi/apply_ddgi.c.hlsl",						"main",
	"ddgi/ddgi_debug.vv.hlsl",						"main",
	"ddgi/ddgi_debug.p.hlsl",						"main",
	"svgf/svgf_prepass.c.hlsl",						"main",
	"svgf/svgf_temporal.c.hlsl",					"main",
	"svgf/svgf_atrous.c.hlsl",						"main",
	"xess_velocity.c.hlsl",							"main",
	"ts_normal_to_deriv.c.hlsl",					"main",
	"triplanar.vv.hlsl",							"main",
	"triplanar.p.hlsl",								"main",
	"debug.p.hlsl",									"main",
};

//	EOF
