#pragma once

enum ShaderName
{
	DepthOpaqueVV,
	DepthMaskedVV,
	DepthMaskedP,
	MeshVV,
	MeshOpaqueP,
	MeshMaskedP,
	VisibilityOpaqueVV,
	VisibilityOpaqueP,
	VisibilityMaskedVV,
	VisibilityMaskedP,
	LightingC,
	IndirectC,
	FullscreenVV,
	TonemapP,
	ClassifyC,
	MatDepthP,
	ClearArgC,
	MaterialTileVV,
	MaterialTileP,
	ShadowOpaqueVV,
	ShadowMaskedVV,
	ShadowMaskedP,
	ShadowP,
	BlurP,
	NormalToDerivC,
	TriplanarVV,
	TriplanarP,
	MaterialTileTriplanarP,
	SsaoHbaoC,
	SsaoBitmaskC,
	SsgiC,
	SsgiDIC,
	DenoiseC,
	DenoiseWithGIC,
	DeinterleaveC,
	MeshletCullC,
	ClearMipC,
	FeedbackMipC,
	VisibilityMesh1stA,
	VisibilityMesh2ndA,
	VisibilityMeshOpaqueM,
	VisibilityMeshOpaqueP,
	VisibilityMeshMaskedM,
	VisibilityMeshMaskedP,
	DepthReductionP,
	DepthReductionC,
	MaterialResolveLib,
	PrefixSumInitCS,
	PrefixSumC,
	InitCountC,
	CountC,
	CountSumC,
	BinningC,
	FinalizeC,
	MatGBStandardC,
	MatGBTriplanarC,
	InitBinningTileC,
	BinningTileC,
	TileStandardC,
	TileTriplanarC,
	GenVrsC,
	ClearVrsC,
	ReprojectVrsC,
	MotionVectorC,
	MakeIrradianceC,
	MeshXluVV,
	MeshXluP,
	RTTestLib,
	RTProbeTraceLib,
	RTRestirGILib,
	RTMaterialLib,
	ApplyDDGI,
	DebugP,
	DDGIDebugVV,
	DDGIDebugP,

	MAX
};

static const char* kShaderFileAndEntry[] = {
	"depth_opaque.vv.hlsl",				"main",
	"depth_masked.vv.hlsl",				"main",
	"depth_masked.p.hlsl",				"main",
	"mesh.vv.hlsl",						"main",
	"mesh_opaque.p.hlsl",				"main",
	"mesh_masked.p.hlsl",				"main",
	"visibility_opaque.vv.hlsl",		"main",
	"visibility_opaque.p.hlsl",			"main",
	"visibility_masked.vv.hlsl",		"main",
	"visibility_masked.p.hlsl",			"main",
	"lighting.c.hlsl",					"main",
	"indirect_lighting.c.hlsl",			"main",
	"fullscreen.vv.hlsl",				"main",
	"tonemap.p.hlsl",					"main",
	"classify.c.hlsl",					"main",
	"material_depth.p.hlsl",			"main",
	"clear_arg.c.hlsl",					"main",
	"material_tile.vv.hlsl",			"main",
	"material_tile.p.hlsl",				"main",
	"shadow_opaque.vv.hlsl",			"main",
	"shadow_masked.vv.hlsl",			"main",
	"shadow_masked.p.hlsl",				"main",
	"shadow.p.hlsl",					"main",
	"blur.p.hlsl",						"main",
	"ts_normal_to_deriv.c.hlsl",		"main",
	"triplanar.vv.hlsl",				"main",
	"triplanar.p.hlsl",					"main",
	"material_tile_triplanar.p.hlsl",	"main",
	"ssao_hbao.c.hlsl",					"main",
	"ssao_bitmask.c.hlsl",				"main",
	"ssgi_standard.c.hlsl",				"main",
	"ssgi_deinterleave.c.hlsl",			"main",
	"denoise.c.hlsl",					"main",
	"denoise_with_gi.c.hlsl",			"main",
	"deinterleave.c.hlsl",				"main",
	"meshlet_cull.c.hlsl",				"main",
	"miplevel_feedback.c.hlsl",			"ClearCS",
	"miplevel_feedback.c.hlsl",			"FeedbackCS",
	"visibility_mesh_1st.a.hlsl",		"main",
	"visibility_mesh_2nd.a.hlsl",		"main",
	"visibility_mesh_opaque.m.hlsl",	"main",
	"visibility_mesh_opaque.p.hlsl",	"main",
	"visibility_mesh_masked.m.hlsl",	"main",
	"visibility_mesh_masked.p.hlsl",	"main",
	"depth_reduction.p.hlsl",			"main",
	"depth_reduction.c.hlsl",			"main",
	"material_resolve.lib.hlsl",		"main",
	"prefix_sum.c.hlsl",				"InitBufferCS",
	"prefix_sum.c.hlsl",				"PrefixScanCS",
	"material_binning.c.hlsl",			"InitCountCS",
	"material_binning.c.hlsl",			"CountCS",
	"material_binning.c.hlsl",			"CountSumCS",
	"material_binning.c.hlsl",			"BinningCS",
	"material_binning.c.hlsl",			"FinalizeCS",
	"material_gbuffer.c.hlsl",			"StandardCS",
	"material_gbuffer.c.hlsl",			"TriplanarCS",
	"material_binning.c.hlsl",			"InitBinningTileCS",
	"material_binning.c.hlsl",			"BinningTileCS",
	"material_tile.c.hlsl",				"StandardCS",
	"material_tile.c.hlsl",				"TriplanarCS",
	"vrs.c.hlsl",						"GenerateVrsCS",
	"vrs.c.hlsl",						"ClearCS",
	"vrs.c.hlsl",						"ReprojectionCS",
	"motion_vector.c.hlsl",				"main",
	"make_irradiance.c.hlsl",			"main",
	"mesh_xlu.vv.hlsl",					"main",
	"mesh_xlu.p.hlsl",					"main",
	"rt_test.lib.hlsl",					"main",
	"rt_probe_trace.lib.hlsl",			"main",
	"rt_restir_gi.lib.hlsl",			"main",
	"rt_material.lib.hlsl",				"main",
	"apply_ddgi.c.hlsl",				"main",
	"debug.p.hlsl",						"main",
	"ddgi_debug.vv.hlsl",				"main",
	"ddgi_debug.p.hlsl",				"main",
};

//	EOF
