#ifndef CONSTANT_DEFS_H
#define CONSTANT_DEFS_H

#define CLASSIFY_TILE_WIDTH (64)
#define CLASSIFY_THREAD_WIDTH (16)
#define CLASSIFY_MATERIAL_CHUNK_MAX (256)
#define CLASSIFY_MATERIAL_MAX (CLASSIFY_MATERIAL_CHUNK_MAX * 32)
#define CLASSIFY_DEPTH_RANGE CLASSIFY_MATERIAL_MAX

#define TILE_THREADS_WIDTH  8
#define PIXEL_QUAD_WIDTH    2
#define TILE_PIXEL_WIDTH    (TILE_THREADS_WIDTH * PIXEL_QUAD_WIDTH)

#endif // CONSTANT_DEFS_H
//  EOF
